# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

before_install:
    - sh ./install_buck.sh

language: android
jdk: oraclejdk7

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-android-m2repository
    - extra-android-support

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - touch buildSrc/bintray.properties

script:
  - bash ./gradlew okbuck && ./buck/bin/buck install --run appDevDebug && ./buck/bin/buck install --run appDevRelease && ./buck/bin/buck install --run appProdDebug && ./buck/bin/buck install --run appProdRelease && ./buck/bin/buck install --run anotherappDebug && ./buck/bin/buck install --run anotherappRelease

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
