# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

before_install:
    - sh ./install_buck.sh

language: android
jdk: oraclejdk7

android:
  components:
    - android-23
    - build-tools-23.0.3
    - extra-android-m2repository
    - extra-android-support

# Emulator Management: Create, Start and Wait
before_script:
  - touch buildSrc/bintray.properties

script:
  - bash ./gradlew okbuck && ./buck/bin/buck build appDevDebug && ./buck/bin/buck build appDevRelease && ./buck/bin/buck build appProdDebug && ./buck/bin/buck build appProdRelease && ./buck/bin/buck build another-appDebug && ./buck/bin/buck build another-appRelease

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
