# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

before_install:
    - bash git clone https://github.com/facebook/buck.git && cd buck && ant

language: android
jdk: oraclejdk8

android:
  components:
    - android-23
    - build-tools-23.0.3
    - extra-android-m2repository
    - extra-android-support

# Emulator Management: Create, Start and Wait
script:
  - bash ./gradlew okbuck && ./buck/bin/buck build appDevDebug appDevRelease appProdDebug appProdRelease another-appDebug another-appRelease

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
